# Calculating Across Rows

How do we calculate row-wise in Pandas like we do in Excel?

<img src="https://sandeepmj.github.io/image-host/oil-v-gold.png">

We need a couple of new concepts to do this calculation:

1. Capture a number from a cell and hold in variable.
2. We `apply()`calculations across columns, row-wise, using using a `lambda expression`.


This is step one in your ability to accomplish tasks that are highly specialized to your beats.

In [1]:
## import library
import pandas as pd

In [2]:
## pull in data
df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/oil-v-gold-pandas.csv")
df

         Date  PX_GOLD  PX_OIL
0     1/31/08    922.7   91.75
1     2/29/08    975.0  101.84
2     3/31/08    916.2  101.58
3     4/30/08    865.1  113.46
4     5/30/08    887.3  127.35
..        ...      ...     ...
116   9/29/17   1281.5   51.67
117  10/31/17   1270.5   54.38
118  11/30/17   1273.2   57.40
119  12/29/17   1309.3   60.42
120   1/31/18   1339.0   64.73

[121 rows x 3 columns]

What are the different values for row **TWO** in this formula for `PX_GOLD`:

$$\text{Pct Chg at time } t = \frac{\text{Value at time } t - \text{Value at start time}}{\text{Value at start time}} \times 100$$

In [ ]:
### Lambda expression, .iat = index at, holds a row value as an index starting point

Use `.iat` to store a value from a specific cell into a variable:

```dataframe["column_name"].iat[row_index_number]```

In [3]:
## hold gold
df["PX_GOLD"].iat[0]

np.float64(922.7)

Also works:

`dataframe.iat[col_index_number, row_index_number]`

In [5]:
## hold gold col index, row index
gold_start = df.iat[0,1]
gold_start

np.float64(922.7)

Place the value for the starting oil price in a variable called `oil_baseline`

In [8]:
## oil_baseline

oil_start = df["PX_OIL"].iat[0]
oil_start

np.float64(91.75)

# `lambda expressions`

We're going to just write one first and then break it down:

In [33]:
## create a new column that holds the zero index for gold

df["gold_zero_index"] = df["PX_GOLD"].apply(lambda x:round((x-gold_start)/gold_start*100, 2))
df

,Date,PX_GOLD,PX_OIL,gold_zero_index,oil_zero_index,gold_100_index,oil_100_index
0,1/31/08,922.7,91.75,0.00,0.00,100.00,100.00
1,2/29/08,975.0,101.84,5.67,11.00,105.67,111.00
2,3/31/08,916.2,101.58,-0.70,10.71,99.30,110.71
3,4/30/08,865.1,113.46,-6.24,23.66,93.76,123.66
4,5/30/08,887.3,127.35,-3.84,38.80,96.16,138.80
...,...,...,...,...,...,...,...
116,9/29/17,1281.5,51.67,38.89,-43.68,138.89,56.32
117,10/31/17,1270.5,54.38,37.69,-40.73,137.69,59.27
118,11/30/17,1273.2,57.40,37.99,-37.44,137.99,62.56
119,12/29/17,1309.3,60.42,41.90,-34.15,141.90,65.85
120,1/31/18,1339.0,64.73,45.12,-29.45,145.12,70.55

## What  `x` stand for:

- In Pandas, we `apply()` lambda expressions to columns.
-  `.apply()`  works element-wise on each value in the `PX_GOLD` column, one at a time.
- `x` is a single value representing a cell in the column `PX_GOLD`
- The ```lambda x:``` processes each row of a dataframe, one row at a time.
-  The `lambda expression` takes each individual number `x` from `PX_GOLD` and runs the indexing formula on it.

Think of it as: "call each value in `PX_GOLD` as `x`, and do this math to using `x` in the formula."

## create a new column that holds the zero index for oil

In [32]:
## zero index oil

df["oil_zero_index"] = df["PX_OIL"].apply(lambda x:round((x-oil_start)/oil_start*100,2))

In [17]:
## call df
df

         Date  PX_GOLD  PX_OIL  gold_zero_index  oil_zero_index
0     1/31/08    922.7   91.75         0.000000        0.000000
1     2/29/08    975.0  101.84         5.668148       10.997275
2     3/31/08    916.2  101.58        -0.704454       10.713896
3     4/30/08    865.1  113.46        -6.242549       23.662125
4     5/30/08    887.3  127.35        -3.836567       38.801090
..        ...      ...     ...              ...             ...
116   9/29/17   1281.5   51.67        38.885878      -43.683924
117  10/31/17   1270.5   54.38        37.693725      -40.730245
118  11/30/17   1273.2   57.40        37.986344      -37.438692
119  12/29/17   1309.3   60.42        41.898775      -34.147139
120   1/31/18   1339.0   64.73        45.117590      -29.449591

[121 rows x 5 columns]

### 100-indexing

Create cells below to add columns for both oil and gold for 100-indexing.

Reminder, the formula for 100-indexing:

$$\text{Index} = \left(\frac{\text{value at time } t}{\text{value at start}}\right) \times 100$$

In [31]:
## gold 100
df["gold_100_index"] = df["PX_GOLD"].apply(lambda x: round(x/gold_start*100, 2))
df

,Date,PX_GOLD,PX_OIL,gold_zero_index,oil_zero_index,gold_100_index,oil_100_index
0,1/31/08,922.7,91.75,0.000000,0.000000,100.00,100.00
1,2/29/08,975.0,101.84,5.668148,10.997275,105.67,111.00
2,3/31/08,916.2,101.58,-0.704454,10.713896,99.30,110.71
3,4/30/08,865.1,113.46,-6.242549,23.662125,93.76,123.66
4,5/30/08,887.3,127.35,-3.836567,38.801090,96.16,138.80
...,...,...,...,...,...,...,...
116,9/29/17,1281.5,51.67,38.885878,-43.683924,138.89,56.32
117,10/31/17,1270.5,54.38,37.693725,-40.730245,137.69,59.27
118,11/30/17,1273.2,57.40,37.986344,-37.438692,137.99,62.56
119,12/29/17,1309.3,60.42,41.898775,-34.147139,141.90,65.85
120,1/31/18,1339.0,64.73,45.117590,-29.449591,145.12,70.55

In [34]:
## oil 100
df["oil_100_index"] = df["PX_OIL"].apply(lambda x: round(x/oil_start*100, 2))
df

,Date,PX_GOLD,PX_OIL,gold_zero_index,oil_zero_index,gold_100_index,oil_100_index
0,1/31/08,922.7,91.75,0.00,0.00,100.00,100.00
1,2/29/08,975.0,101.84,5.67,11.00,105.67,111.00
2,3/31/08,916.2,101.58,-0.70,10.71,99.30,110.71
3,4/30/08,865.1,113.46,-6.24,23.66,93.76,123.66
4,5/30/08,887.3,127.35,-3.84,38.80,96.16,138.80
...,...,...,...,...,...,...,...
116,9/29/17,1281.5,51.67,38.89,-43.68,138.89,56.32
117,10/31/17,1270.5,54.38,37.69,-40.73,137.69,59.27
118,11/30/17,1273.2,57.40,37.99,-37.44,137.99,62.56
119,12/29/17,1309.3,60.42,41.90,-34.15,141.90,65.85
120,1/31/18,1339.0,64.73,45.12,-29.45,145.12,70.55

# Homework

<a href="https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/demo-data-solutions/cablebill-v-income.csv">This dataset</a> shows the price of a standard cable subscription and the U.S. median income annually between 1995-2023.

Has median income kept pace with the price of a cable subscription?

Round all numbers to 1 decimal place

In [35]:
## read file
df_cable = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/demo-data-solutions/cablebill-v-income.csv")
df_cable

    year  avg_cable_bill  median_household_income
0   1995           22.35                    35249
1   1996           23.28                    36689
2   1997           26.31                    38229
3   1998           27.88                    40148
4   1999           28.94                    41994
5   2000           31.22                    42349
6   2001           33.75                    42710
7   2002           36.47                    43057
8   2003           38.95                    43564
9   2004           41.04                    44684
10  2005           43.04                    46242
11  2006           43.26                    48451
12  2007           47.27                    50740
13  2008           49.65                    52029
14  2009           52.37                    50221
15  2010           54.44                    50046
16  2011           57.46                    50502
17  2012           61.63                    51371
18  2013           69.18                    52250
19  2014           71.45                    53657
20  2015           78.42                    55775
21  2016          150.98                    57617
22  2017          168.49                    61372
23  2018          199.99                    64324
24  2019          210.84                    69560
25  2020          217.42                    67521
26  2021          231.10                    70784
27  2022          251.48                    74580
28  2023          291.81                    75143

In [36]:
## get info
df_cable.info()

<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   year                     29 non-null     int64
 1   avg_cable_bill           29 non-null     float64
 2   median_household_income  29 non-null     int64
dtypes: float64(1), int64(2)
memory usage: 828.0 bytes

### Index cable billl

In [37]:
## cable_baseline

cable_baseline = df_cable["avg_cable_bill"].iat[0]
cable_baseline

np.float64(22.35)

In [38]:
## cable bill index

df_cable["cable_zero_index"] = df_cable["avg_cable_bill"].apply(lambda x:round((x-cable_baseline)/cable_baseline*100,2))
df_cable

    year  avg_cable_bill  median_household_income  cable_zero_index
0   1995           22.35                    35249              0.00
1   1996           23.28                    36689              4.16
2   1997           26.31                    38229             17.72
3   1998           27.88                    40148             24.74
4   1999           28.94                    41994             29.49
5   2000           31.22                    42349             39.69
6   2001           33.75                    42710             51.01
7   2002           36.47                    43057             63.18
8   2003           38.95                    43564             74.27
9   2004           41.04                    44684             83.62
10  2005           43.04                    46242             92.57
11  2006           43.26                    48451             93.56
12  2007           47.27                    50740            111.50
13  2008           49.65                    52029            122.15
14  2009           52.37                    50221            134.32
15  2010           54.44                    50046            143.58
16  2011           57.46                    50502            157.09
17  2012           61.63                    51371            175.75
18  2013           69.18                    52250            209.53
19  2014           71.45                    53657            219.69
20  2015           78.42                    55775            250.87
21  2016          150.98                    57617            575.53
22  2017          168.49                    61372            653.87
23  2018          199.99                    64324            794.81
24  2019          210.84                    69560            843.36
25  2020          217.42                    67521            872.80
26  2021          231.10                    70784            934.00
27  2022          251.48                    74580           1025.19
28  2023          291.81                    75143           1205.64

### Index median income

In [39]:
## income_baseline

income_baseline = df_cable["median_household_income"].iat[0]
income_baseline

np.int64(35249)

In [40]:
## median income index

df_cable["income_zero_index"] = df_cable["median_household_income"].apply(lambda x:round((x-income_baseline)/income_baseline*100,2))
df_cable

,year,avg_cable_bill,median_household_income,cable_zero_index,income_zero_index
0,1995,22.35,35249,0.00,0.00
1,1996,23.28,36689,4.16,4.09
2,1997,26.31,38229,17.72,8.45
3,1998,27.88,40148,24.74,13.90
4,1999,28.94,41994,29.49,19.14
5,2000,31.22,42349,39.69,20.14
6,2001,33.75,42710,51.01,21.17
7,2002,36.47,43057,63.18,22.15
8,2003,38.95,43564,74.27,23.59
9,2004,41.04,44684,83.62,26.77
10,2005,43.04,46242,92.57,31.19
11,2006,43.26,48451,93.56,37.45
12,2007,47.27,50740,111.50,43.95
13,2008,49.65,52029,122.15,47.60
14,2009,52.37,50221,134.32,42.47
15,2010,54.44,50046,143.58,41.98
16,2011,57.46,50502,157.09,43.27
17,2012,61.63,51371,175.75,45.74
18,2013,69.18,52250,209.53,48.23
19,2014,71.45,53657,219.69,52.22
20,2015,78.42,55775,250.87,58.23
21,2016,150.98,57617,575.53,63.46
22,2017,168.49,61372,653.87,74.11
23,2018,199.99,64324,794.81,82.48
24,2019,210.84,69560,843.36,97.34
25,2020,217.42,67521,872.80,91.55
26,2021,231.10,70784,934.00,100.81
27,2022,251.48,74580,1025.19,111.58
28,2023,291.81,75143,1205.64,113.18

In [42]:
## analysis
print(f"Since 1955, the average cable bill has increasingly outpaced the median household income. By 2023, while the median income has doubled, cable prices have increased twelvefold.")

Since 1955, the average cable bill has increasingly outpaced the median household income. By 2023, while the median income has doubled, cable prices have increased twelvefold.